apiVersion: v1
kind: Service
metadata:
  name: transcription-service
spec:
  type: LoadBalancer
  selector:
    app: transcription-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80