---
apiVersion: v1
kind: Namespace
metadata:
  name: transcriptor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: transcriptor
  name: deployment-transcriptor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-transcriptor
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-transcriptor
    spec:
      containers:
      - name: app-transcriptor
        image: juancastillos/transcriptor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80