apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriptor
  labels:
    app: transcriptor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transcriptor
  template:
    metadata:
      labels:
        app: transcriptor
    spec:
      containers:
      - name: transcriptor
        image: juancastillos/transcriptor:latest
        ports:
        - containerPort: 5000