apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: eks.18.216.240.244.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transcriptor-service
            port:
              number: 80