apiVersion: app/v1
kind: Service
metadata:
  name: transcriptor
  labels:
    app: transcriptor-service
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: transcriptor
  spec:
    containers:
    - name: transcriptor
      image: juancastillos/transcriptor:latest
      ports:
      - containerPort: 8000