apiVersion: v1
kind: Service
metadata:
  name: transcriptor-service  # Nombre del servicio
  labels:
    app: transcriptor
spec:
  type: LoadBalancer           # Expone el servicio externamente con una IP pública
  selector:                    # Debe coincidir con las etiquetas del Deployment
    app: transcriptor
  ports:
    - protocol: TCP
      port: 80                 # Puerto externo para acceder al servicio
      targetPort: 8000         # Puerto dentro del contenedor donde está corriendo FastAPI