name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11.0'

  #     - name: Install Dependencies
  #       run: |
  #         python -m venv .venv
  #         source .venv/bin/activate
  #         pip install -r requirements.txt

  #     - name: Run Tests
  #       run: |
  #         source .venv/bin/activate
  #         pytest --maxfail=1 --disable-warnings -q
  

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t juancastillos/transcriptor:latest .
          docker push juancastillos/transcriptor:latest

          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-2 --name devops-cluster-eks
          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f eks/ingressclass.yaml
          kubectl apply -f eks/deployment.yaml
          kubectl apply -f eks/service.yaml